import type { Service, Project, Testimonial, ProcessStep, Stat, NavLink } from "@/types";

export const NAV_LINKS: NavLink[] = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Services", href: "/services" },
  { label: "Projects", href: "/projects" },
  { label: "Process", href: "/process" },
  { label: "Testimonials", href: "/testimonials" },
  { label: "Contact", href: "/contact" },
];

export const STATS: Stat[] = [
  { label: "Years of Experience", value: 18, suffix: "+", icon: "Award" },
  { label: "Projects Completed", value: 340, suffix: "+", icon: "Building2" },
  { label: "Happy Clients", value: 290, suffix: "+", icon: "Users" },
  { label: "Professional Engineers", value: 45, suffix: "+", icon: "HardHat" },
];

export const SERVICES: Service[] = [
  {
    id: "basement",
    title: "Basement Construction",
    description: "Expert excavation, waterproofing, and structural basement builds designed to last generations.",
    icon: "Layers",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80",
    features: ["Deep excavation", "Waterproofing systems", "Structural reinforcement", "Utility rough-ins"],
    href: "/services#basement",
  },
  {
    id: "structural",
    title: "Structural Construction",
    description: "From foundation to frame — precision structural engineering for safe, durable homes.",
    icon: "Building2",
    image: "https://images.unsplash.com/photo-1590859808308-3d2d9c515b1a?w=600&q=80",
    features: ["Steel & concrete framing", "Load-bearing walls", "Seismic compliance", "Roofing systems"],
    href: "/services#structural",
  },
  {
    id: "electrical",
    title: "Electrical Installation",
    description: "Complete electrical systems — panels, wiring, smart home integration, and safety certification.",
    icon: "Zap",
    image: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=600&q=80",
    features: ["Panel installation", "Full wiring", "Smart home ready", "Code compliance"],
    href: "/services#electrical",
  },
  {
    id: "plumbing",
    title: "Plumbing Systems",
    description: "Full residential plumbing — supply lines, drainage, fixtures, and water heater installation.",
    icon: "Droplets",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    features: ["Supply & drain lines", "Fixture installation", "Water heaters", "Leak testing"],
    href: "/services#plumbing",
  },
  {
    id: "interior",
    title: "Interior Finishing",
    description: "Premium interior craftsmanship — flooring, painting, cabinetry, trim, and custom millwork.",
    icon: "PaintBucket",
    image: "https://images.unsplash.com/photo-1631889993959-41b4e9c6e3c5?w=600&q=80",
    features: ["Hardwood flooring", "Custom cabinetry", "Paint & texture", "Trim & millwork"],
    href: "/services#interior",
  },
  {
    id: "turnkey",
    title: "Turnkey House Construction",
    description: "Complete home delivery from empty lot to move-in ready — we handle everything end-to-end.",
    icon: "Key",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=600&q=80",
    features: ["Site to move-in", "Single contract", "On-time delivery", "Post-build support"],
    href: "/services#turnkey",
  },
];

export const PROJECTS: Project[] = [
  {
    id: "lakeside-villa",
    title: "Lakeside Villa",
    location: "Austin, TX",
    year: 2024,
    category: "Turnkey",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",
    description: "5-bedroom lakefront property with panoramic views, custom pool, and smart home integration.",
    area: "4,800 sq ft",
    duration: "14 months",
  },
  {
    id: "urban-townhouse",
    title: "Urban Townhouse Complex",
    location: "Denver, CO",
    year: 2024,
    category: "Structural",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    description: "8-unit contemporary townhouse development with shared courtyard and underground parking.",
    area: "12,400 sq ft",
    duration: "18 months",
  },
  {
    id: "mountain-retreat",
    title: "Mountain Retreat",
    location: "Aspen, CO",
    year: 2023,
    category: "Turnkey",
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&q=80",
    description: "Luxury mountain chalet with cedar exterior, floor-to-ceiling windows, and radiant heating.",
    area: "3,600 sq ft",
    duration: "11 months",
  },
  {
    id: "modern-family-home",
    title: "The Mercer Residence",
    location: "Portland, OR",
    year: 2023,
    category: "Interior",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
    description: "Mid-century modern family home with open concept living and designer kitchen.",
    area: "2,900 sq ft",
    duration: "9 months",
  },
  {
    id: "coastal-estate",
    title: "Coastal Estate",
    location: "Malibu, CA",
    year: 2023,
    category: "Turnkey",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
    description: "Ocean-facing estate with infinity pool, rooftop terrace, and storm-resistant construction.",
    area: "6,200 sq ft",
    duration: "20 months",
  },
  {
    id: "heritage-renovation",
    title: "Heritage Home Renovation",
    location: "Boston, MA",
    year: 2022,
    category: "Interior",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
    description: "Full gut renovation of a 1920s brownstone preserving historic character with modern amenities.",
    area: "3,100 sq ft",
    duration: "13 months",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "t1",
    name: "Michael & Sarah Chen",
    role: "Homeowners",
    avatar: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=100&q=80",
    review: "Khushi Construction & Land Developers turned our dream into reality. The team was professional, transparent, and delivered on time. Our lakeside villa exceeded every expectation. We couldn't be happier.",
    rating: 5,
    project: "Lakeside Villa",
  },
  {
    id: "t2",
    name: "James Rodriguez",
    role: "Real Estate Developer",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
    review: "I've worked with 6 contractors over 12 years. Khushi Construction & Land Developers is in a different league — their project management, material quality, and craftsmanship set the standard.",
    rating: 5,
    project: "Urban Townhouse Complex",
  },
  {
    id: "t3",
    name: "Amanda Foster",
    role: "Interior Designer",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    review: "As a designer who works closely with builders, precision matters. Khushi Construction & Land Developers' finishing team delivers museum-quality workmanship every single time.",
    rating: 5,
    project: "The Mercer Residence",
  },
  {
    id: "t4",
    name: "David & Lisa Park",
    role: "Homeowners",
    avatar: "https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=100&q=80",
    review: "From our first consultation to handing over the keys, everything was seamless. The dedicated project manager kept us informed every step of the way.",
    rating: 5,
    project: "Mountain Retreat",
  },
  {
    id: "t5",
    name: "Thomas Wright",
    role: "Property Investor",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    review: "Three projects completed with Khushi Construction & Land Developers — all delivered on budget, on time. Their turnkey solution eliminates all the usual headaches. Highly recommended.",
    rating: 5,
    project: "Coastal Estate",
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  { id: 1, title: "Initial Consultation", description: "We meet to understand your vision, site conditions, and budget requirements before anything else.", icon: "MessageSquare", duration: "1-2 days" },
  { id: 2, title: "Design & Planning", description: "Architects and engineers develop detailed blueprints and 3D models for your approval.", icon: "PenTool", duration: "2-4 weeks" },
  { id: 3, title: "Budget Estimation", description: "Transparent, itemized cost breakdown with no hidden fees — you know exactly where every dollar goes.", icon: "Calculator", duration: "1 week" },
  { id: 4, title: "Foundation & Basement", description: "Expert excavation, forming, and concrete work to establish a rock-solid foundation.", icon: "Layers", duration: "3-6 weeks" },
  { id: 5, title: "Structural Construction", description: "Steel or wood framing, roofing systems, and exterior envelope installation.", icon: "Building2", duration: "6-12 weeks" },
  { id: 6, title: "MEP Installation", description: "Rough-in of all mechanical, electrical, and plumbing systems before walls are closed.", icon: "Zap", duration: "4-8 weeks" },
  { id: 7, title: "Interior Finishing", description: "Insulation, drywall, flooring, paint, cabinetry, fixtures, and all fine details.", icon: "PaintBucket", duration: "6-10 weeks" },
  { id: 8, title: "Final Inspection", description: "Comprehensive walkthrough, municipal inspections, and punch list completion.", icon: "ClipboardCheck", duration: "1-2 weeks" },
  { id: 9, title: "Handover & Support", description: "Keys delivered with full documentation, warranties, and 12-month post-build support.", icon: "Key", duration: "1 day" },
];
